---
- name: Untaint control plane node
  hosts: all
  become: true
  tasks:
    - name: Remove NoSchedule taint from control plane
      command: kubectl taint nodes k8s-control-plane node-role.kubernetes.io/control-plane:NoSchedule-
      become_user: vagrant
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: untaint_result
      failed_when:
        - untaint_result.rc != 0
        - '"not found" not in untaint_result.stderr'
      changed_when: '"untainted" in untaint_result.stdout'

    - name: Verify control plane is schedulable
      shell: kubectl describe node k8s-control-plane | grep -i taint || echo "No taints"
      become_user: vagrant
      environment:
        KUBECONFIG: /home/vagrant/.kube/config
      register: taint_check

    - name: Display taint status
      debug:
        msg: "{{ taint_check.stdout_lines }}"
